default:
  @just --list

import:
  godot --headless --path . --import

run:
  godot --headless --path . --scene res://scenes/server_main.tscn

docker-build:
  docker build -f ../../deploy/docker/game-server/Dockerfile -t evanopolis-game-server ../..

docker-run:
  test -n "${AUTH_BASE_URL:-}" || (echo "AUTH_BASE_URL is required"; exit 1)
  docker run --rm --init --network host \
    -e AUTH_BASE_URL="${AUTH_BASE_URL}" \
    -e AUTH_VERIFY_PATH="${AUTH_VERIFY_PATH:-}" \
    -e ROOMS_API_BASE_URL="${ROOMS_API_BASE_URL:-}" \
    -e ROOMS_API_LOOKUP_TEMPLATE="${ROOMS_API_LOOKUP_TEMPLATE:-}" \
    -e GAME_SERVER_PORT="${GAME_SERVER_PORT:-9010}" \
    evanopolis-game-server

test:
  godot --headless --path . --log-file /tmp/evanopolis-game-server-gut.log -s addons/gut/gut_cmdln.gd -gconfig=res://.gutconfig.json -gexit
